### ISSUE TITLE
Cubs and White Sox Are Reversed In Teams Table

### ISSUE THREAD

**Issue by cdalzell** [cdalzell/Lahman#13]
Issue reported via email:

>I'm not sure if this error goes upstream, but in the most recent version of the R package, the names
for the Cubs and White Sox are reversed in the Teams table. 
>
>```r
>require(dplyr)
>require(Lahman)
>
>Teams %>%
>  filter(teamID %in% c("CHA", "CHN") & yearID > 2010) %>%
>  select(yearID, teamID, name)
>```
>
>The names should be reversed for 2013 and 2014.

**Comment by cdalzell** [comment]
This appears to be a known issue. I'll work on a fix to push to the develop branch as the 2015 data update shouldn't be too far off in the future.

**Comment by cdalzell** [comment]
Informed the issue reporter via email that I've pushed a fix in feature/#13-Cubs_White_Sox_Teams_Issue.

```r
library(devtools)
dev_mode()

# this is going to take a bit of time, there's a lot more in the github project that gets
# dropped from the CRAN library
install_github("cdalzell/Lahman", ref="feature/%2313-Cubs_White_Sox_Teams_Issue")

library(dplyr)

Teams %>%
 filter(teamID %in% c("CHA", "CHN") & yearID > 2010) %>%
 select(yearID, teamID, name)

dev_mode()
```

If this looks OK I'll merge the change to develop and close the issue. Will need to keep an eye on this once the 2015 data is released.

**Comment by djmurphy420** [comment]
Hi Chris:
This seems like something that should be brought to the attention of Sean Lahman directly. Why don't you forward the result to him?
Dennis 


     On Wednesday, October 28, 2015 7:47 PM, Chris Dalzell <notifications@github.com> wrote:
   

 Informed the issue reporter via email that I've pushed a fix in feature/#13-Cubs_White_Sox_Teams_Issue.library(devtools)
dev_mode()

# this is going to take a bit of time, there's a lot more in the github project that gets
# dropped from the CRAN library
install_github("cdalzell/Lahman", ref="feature/%2313-Cubs_White_Sox_Teams_Issue")

library(dplyr)

Teams %>%
 filter(teamID %in% c("CHA", "CHN") & yearID > 2010) %>%
 select(yearID, teamID, name)

dev_mode()If this looks OK I'll merge the change to develop and close the issue. Will need to keep an eye on this once the 2015 data is released.—

**Comment by beanumber** [comment]
Response from Sean:

https://twitter.com/seanlahman/status/659725456904749057?cn=cmVwbHk%3D

**Comment by cdalzell** [comment]
Thanks all for following up with Sean, I was going to this evening but now I've one less thing to do before Halloween festivities. :)

@beanumber Did the workaround look OK for you?

**Comment by MonkmanMH** [comment]
Just catching up on the notifications now (I need to stop watching ggplot2 ... too much traffic for something I don't really participate in!)

This issue is something I raised with Sean Lahman back in late 2014, but the data bug persisted in the next iteration of the database.

And it's not just a reversal of the team names; here's the full text of the details:

> (Lahman database release 2014-02-14).  In the table "Teams", the last 8 columns of the Chicago
> White Sox row are switched with the same cells from the Cubs row.
>
> The problem seems to start (looking at the CSV file version of the table) with the "name" field, and
> continues through the remainder of the table:  "park", "attendance", "BPF", "PFF", "teamIDBR", 
> "teamIDlahman45", and "teamIDretro".

**Comment by friendly** [comment]
As I said in #14 the thing to do for now is document these problems.  Hopefully @seanlahman
will fix them in the master db we rely on.

Maybe these issues, labeled as bug, are sufficient.  Alternatively, a script to make corrections?

**Comment by seanlahman** [comment]
I'll fix this one, and any others you let me know about. 

This particular one got fixed and then somehow reverted.

**Comment by seanlahman** [comment]
This issue can be closed.  The data has been corrected, and I discovered a bug in my code that was causing this.
